(define-module (generate-template)
  #:use-module (cairo)
  #:use-module (lib cairo)
  #:use-module (lib date)
  #:use-module (templates agendamento3x3)
  #:export (generate-template))

(define* (generate-template #:key filepath year)
  (define page A5)
  (define s (cairo-pdf-surface-create (width page) (height page) filepath))
  (define cr (cairo-create s))
  (agendamento3x3 cr #:page page #:from (make-date-ymd year 1) #:to (make-date-ymd year 12 31))
  (cairo-destroy cr)
  (cairo-surface-destroy s))
